Update Gazebo
sea-bass/turtlebot3_behavior_demos pull request #51
Opened 2024-12-09 15:16 UTC by elsayedelsheikh

Closes (#44), Tested with ros2-rolling with a few tasks left:
- [ ] Update block spawner 
- [ ] Add set_init_amcl_pose (/or) use [nav2_params.yaml](https://github.com/ros-navigation/navigation2/blob/add09f60b17f6134416122f8285eba7268d275d7/nav2_bringup/params/nav2_params.yaml#L1) to initialize robot pose.  

We are gonna need to update `/cmd_vel` publishers as nav2 has migrated to `TwistStamped` message for `/cmd_vel` topics a few days ago.

![Screenshot from 2024-12-09 17-10-23](https://github.com/user-attachments/assets/cfdbd18d-232e-4c82-971e-082c0dd2cb3c)

Should go for the latest update with `TwistStamped` messages and update docker file as well ?

2024-12-09 16:26 UTC, sea-bass commented on tb3_worlds/launch/tb3_world.launch.py
> +# Copyright (C) 2023 Open Source Robotics Foundation
Should this OSRF copyright be here? If it's directly copied over, then probably right to attribute it, but otherwise maybe not.

2024-12-09 16:26 UTC, sea-bass commented on dependencies.repos
> +  # TurtleBot4 Repo
So the world file and examples still have a TurtleBot 3, but this now is bring in a TurtleBot4 repo?

I'm okay with either robot, but we should be consistent. Probably prefer the 4 since it's newer.

2024-12-09 17:32 UTC, elsayedelsheikh commented
> Amazing!
> 
> Is the `TwistStamped` update only for Rolling, or will it be backported/possible in Humble/Jazzy as well?
> 
> I think I would maybe bias towards what is going to be possible in Jazzy. For Humble, the current version of the repo is fine if needed.
> 
> Edit: I see it's going in for Jazzy (https://discourse.ros.org/t/nav2-support-for-twiststamped-available-rolling-jazzy/35995). In that case, yes let's update.

Great! Moving forward with `TwistStamped`. I believe there's no need to update the Docker files for now. With this, the repository now supports ROS2 Humble and the latest distribution.

2024-12-09 17:38 UTC, elsayedelsheikh commented
> So the world file and examples still have a TurtleBot 3, but this now is bring in a TurtleBot4 repo?
> 
> I'm okay with either robot, but we should be consistent. Probably prefer the 4 since it's newer.

We can have both turtlebot3 and turtlebot 4 models, I'll add an extra argument to specify which model to use in `tb3_demo_world.launch.yaml`
```yaml
launch:
- arg:
    name: 'use_turtlebot3'
    default: 'False' # False for Turtlebot4
...
- include:
    file: '$(find-pkg-share nav2_bringup)/launch/tb3_simulation_launch.py'
    if: '$(eval "$(var use_turtlebot3) == True")'
...
- include:
    file: '$(find-pkg-share nav2_bringup)/launch/tb4_simulation_launch.py'
    if: '$(eval "$(var use_turtlebot3) == False")'
...
```
![Screenshot from 2024-12-09 19-25-36](https://github.com/user-attachments/assets/c07f3076-2e30-45ea-9c29-b97b1a23dc97)
![Screenshot from 2024-12-09 19-24-36](https://github.com/user-attachments/assets/9ccc19c7-a144-4e48-8d8a-44d0aa535238)

2024-12-09 17:44 UTC, elsayedelsheikh commented on tb3_worlds/launch/tb3_world.launch.py
> +# Copyright (C) 2023 Open Source Robotics Foundation
We needed a launch file for gazebo communicating with ros2 so I've copied this from nav2 and deleted all the extra layers...

2024-12-10 01:50 UTC, sea-bass commented on tb3_worlds/launch/tb3_demo_world_old.launch.py
Feel free to just remove this launch file -- no need to keep it around

2024-12-11 01:07 UTC, sea-bass requested changes
Just did some testing.

At this point, I think it makes sense to default to using Jazzy, for which I have a PR you can stack on top of: https://github.com/sea-bass/turtlebot3_behavior_demos/pull/52

Also, notice that the formatting check is failing. You can run it locally with:

```
pip3 install pre-commit
pre-commit run -a
```

It seems that the `sim` service no longer works since we're not installing the `turtlebot3_gazebo` package any longer. Might want to remove.

```
  # Runs basic TurtleBot3 simulation
  sim:
    extends: overlay
    command: ros2 launch turtlebot3_gazebo turtlebot3_world.launch.py
```

Also, `docker compose run demo-world` also did not succeed for 2 reasons:
* The `launch.py` needs to change to `launch.yaml` -- on second though, should we just keep this as a Python file for consistency?
* There is no `package.xml` dependency on the `nav2_bringup` package. This must be added

Lastly, I tried running this with Jazzy and the robot did not move. This happened in both the TB3 and TB4 case.

On a smaller note, it also seems like the AMCL initial guess never was updated, as it looks off.

![image](https://github.com/user-attachments/assets/588a6a82-45c6-4399-aec8-85dd10306179)

2024-12-11 01:07 UTC, sea-bass commented on tb3_worlds/scripts/set_init_amcl_pose.py
> +        cycle_count += 1
why is this needed? Is this just to shut down the node at some point?

2024-12-11 01:07 UTC, sea-bass requested changes
Just did some testing.

At this point, I think it makes sense to default to using Jazzy, for which I have a PR you can stack on top of: https://github.com/sea-bass/turtlebot3_behavior_demos/pull/52

Also, notice that the formatting check is failing. You can run it locally with:

```
pip3 install pre-commit
pre-commit run -a
```

It seems that the `sim` service no longer works since we're not installing the `turtlebot3_gazebo` package any longer. Might want to replace it with another working sim, maybe the default in this new Nav2 example repo?

```
  # Runs basic TurtleBot3 simulation
  sim:
    extends: overlay
    command: ros2 launch turtlebot3_gazebo turtlebot3_world.launch.py
```

Also, `docker compose run demo-world` also did not succeed for 2 reasons:
* The `launch.py` needs to change to `launch.yaml` -- on second though, should we just keep this as a Python file for consistency?
* There is no `package.xml` dependency on the `nav2_bringup` package. This must be added

Lastly, I tried running this with Jazzy and the robot did not move. This happened in both the TB3 and TB4 case.

On a smaller note, it also seems like the AMCL initial guess never was updated, as it looks off.

![image](https://github.com/user-attachments/assets/588a6a82-45c6-4399-aec8-85dd10306179)

2024-12-11 01:10 UTC, sea-bass commented on tb3_autonomy/src/vision_behaviors.cpp
> +#include <cv_bridge/cv_bridge.hpp>
This seems like it fail on Humble FYI, based on the CI build output

Might want to do something like this: https://github.com/moveit/srdfdom/blob/ros2/include/srdfdom/model.h#L47-L51

2024-12-11 01:20 UTC, sea-bass commented
Oh... Actually my Jazzy PR cannot go in until this PR does, because there is no `gazebo_ros` package (i.e., no Gazebo classic support). Fun :)

2024-12-11 12:21 UTC, elsayedelsheikh commented on tb3_worlds/scripts/set_init_amcl_pose.py
> +        cycle_count += 1
Yes, A timer starts with 0.3 s period and this spins publishing the pose 3 times then shuts down

2024-12-11 12:55 UTC, elsayedelsheikh commented
# Summary
We had to copy almost every launch file in `nav2_minimal_tb3_sim`
- [configs/turtlebot3_waffle_bridge.yaml](https://github.com/ros-navigation/nav2_minimal_turtlebot_simulation/blob/main/nav2_minimal_tb3_sim/configs/turtlebot3_waffle_bridge.yaml) to Add camera bridge and use `Twist` message for `/cmd_vel`
- [launch/spawn_tb3.launch.py](https://github.com/ros-navigation/nav2_minimal_turtlebot_simulation/blob/main/nav2_minimal_tb3_sim/launch/spawn_tb3.launch.py) because it doesn't have an argument for the previous config file
- [urdf/gz_waffle.sdf.xacro](https://github.com/ros-navigation/nav2_minimal_turtlebot_simulation/blob/main/nav2_minimal_tb3_sim/urdf/gz_waffle.sdf.xacro) to add camera plugin

Similarly, for TurtleBot4, we will need to repeat this process. However, I am considering a different approach: creating a batch file to automate these changes in Docker after cloning the repository. This would allow us to either revert to the original implementation using the YAML launch file (or use python launch) for including those in `nav2_minimal_turtlebot_simulation`

2024-12-12 02:40 UTC, sea-bass reviewed
I could get the example to work now! Nav2 works perfectly.

Still a few of my previous comments left over (such as the formatting and the `docker-compose.yaml` updates), plus some new ones I found from being able to test the full example.

Anyways, I did this with Jazzy using my PR in #52, rebased on top of this branch. It's close!

2024-12-12 02:40 UTC, sea-bass commented on tb3_worlds/scripts/set_init_amcl_pose.py
> +        self.declare_parameter("y", value=0.6)
Would it make more sense to keep these parameter defaults as they are, but actually modify the parameters set at runtime in the launch file instead?

2024-12-12 02:40 UTC, sea-bass commented on tb3_worlds/maps/sim_house_locations.yaml
> +location4: [3.2, 0.75, -1.571]
why did these object locations need to change? Isn't the map the same?

Indeed, the navigation targets in the BT example do not position the camera to face the blocks.

When I revert this change, the examples work fine.

2024-12-12 02:40 UTC, sea-bass commented on tb3_worlds/launch/block_spawner.launch.py
> +        mdl_name = "blue_block"
should remove this line, right? `mdl_name` is already a loop variable?

2024-12-12 02:40 UTC, sea-bass commented on tb3_worlds/launch/block_spawner.launch.py
> +                    "z": "0.2",
these blocks are floating in midair, 0.2 is too high a Z value.

2024-12-12 16:24 UTC, elsayedelsheikh commented on tb3_worlds/maps/sim_house_locations.yaml
> +location4: [3.2, 0.75, -1.571]
Ok, I'll revert changes back and test again

2024-12-12 16:24 UTC, elsayedelsheikh commented on tb3_worlds/scripts/set_init_amcl_pose.py
> +        self.declare_parameter("y", value=0.6)
Noted!

2024-12-12 16:39 UTC, elsayedelsheikh commented
> I could get the example to work now! Nav2 works perfectly.
> 
> Still a few of my previous comments left over (such as the formatting and the `docker-compose.yaml` updates), plus some new ones I found from being able to test the full example.
> 
> Anyways, I did this with Jazzy using my PR in #52, rebased on top of this branch. It's close!

I have a VScode Dev container for each distro so I've been using that for testing, and I left the `docker-compose.yaml` updates for #52 PR 

For formatting, Somehow I forgot to push the changes
![image](https://github.com/user-attachments/assets/790cf639-0038-4dd1-ac6c-11cdc4419fe3)

2024-12-12 16:45 UTC, elsayedelsheikh commented on tb3_worlds/maps/sim_house_locations.yaml
> +location4: [3.2, 0.75, -1.571]
Are these correct locations? These ones using my changes
![image](https://github.com/user-attachments/assets/b1434d7f-cfa6-424d-8305-60e8a59d0d3d)

https://github.com/sea-bass/turtlebot3_behavior_demos/blob/ef02d85c86ecf0e2b5ad12b54d4b117fe38e0c65/tb3_worlds/launch/block_spawner.launch.py#L22
Also the original value for this was 0.6 but it gets randomly spawned very far from the wall

Which should we use?

2024-12-12 20:10 UTC, elsayedelsheikh commented
Oops! I forgot to create a ros_gz config file for the turtlebot 4 model since the original one is using TwistStamped for /cmd_vel and has a different topic name for the camera bridge
I will add that in the next few hours

2024-12-12 20:13 UTC, elsayedelsheikh commented
Oops! I forgot to create a ros_gz config file for the turtlebot 4 model since the gazebo topic names are not the same for the 3 and 4 models
I will push that in the next few hours

2024-12-13 01:04 UTC, sea-bass commented on tb3_worlds/maps/sim_house_locations.yaml
> +location4: [3.2, 0.75, -1.571]
The picture looks fine to me... I wonder then why it looked different on my end?

2024-12-13 01:10 UTC, sea-bass commented on tb3_worlds/maps/sim_house_locations.yaml
> +location4: [3.2, 0.75, -1.571]
Ah I see now -- the blocks spawn in the proper locations, but the robot navigates to the wrong poses it seems. The orientation seems wrong and the camera does not face the blocks. What would have changed?

2024-12-13 01:13 UTC, sea-bass commented on tb3_worlds/launch/block_spawner.launch.py
> +                    "z": "0.2",
Is there maybe a way to have the blocks themselves spawn to not be visible by lidar? Or move the robot to be farther away from the blocks at its navigation poses?

2024-12-13 01:22 UTC, sea-bass reviewed
Seems with the latest changes the image topics are down. I am getting nothing published on the `/camera/image_raw` topic.

It appears the Gazebo topic is not echoing either:

```
gz topic -e -t /world/default/model/turtlebot3_waffle/link/camera_link/sensor/intel_realsense_r200_depth/image
```

EDIT: AH -- this should be `turtlebot3` instead of `turtlebot3_waffle` -- you need to fix that in your bridge YAML file.

![image](https://github.com/user-attachments/assets/e6aa067e-13c4-426c-a3d5-ac36ecaac8c5)

2024-12-13 01:57 UTC, sea-bass commented on tb3_worlds/maps/sim_house_locations.yaml
> +location4: [3.2, 0.75, -1.571]
OK for some reason, that offset of `0.6` is needed. The correct values seem to be:

```
location1: [-1.6, -1.1, -2.25]
location2: [-0.1, 3.4, 0.785]
location3: [3.4, -0.1, 1.571]
location4: [2.15, 1.9, -1.571]
```

and `block_spawn_offset = 0.6` -- this needs to be a large value because the robot needs to navigate 0.6 meters away from the blocks.

These values worked for me.

2024-12-13 15:32 UTC, elsayedelsheikh commented on tb3_worlds/launch/block_spawner.launch.py
> +                    "z": "0.2",
Maybe add offset for each location? (Easier and more direct than using cos(theta), sin(theta) - can't change the robot target heading without changing the blocks positions)
```yaml
location1: [-1.6, -1.1, -2.25]
offset1: [0.5,0.3]
```

2024-12-13 17:14 UTC, sea-bass commented on tb3_worlds/launch/block_spawner.launch.py
> +                    "z": "0.2",
Sure. But note that these files get parsed by the autonomy stack as well, in putting together the behavior trees.

2024-12-13 18:23 UTC, elsayedelsheikh commented on tb3_worlds/launch/block_spawner.launch.py
> +                    "z": "0.2",
Great!

2024-12-13 18:48 UTC, elsayedelsheikh commented
I've used this environment variable to choose between turtlebot 3 and turtlebot 4 models
https://github.com/sea-bass/turtlebot3_behavior_demos/blob/187dbf35a4439ed55b5bfa2b79961e48c4da94a5/.env#L4
With the 4 model as the default
https://github.com/sea-bass/turtlebot3_behavior_demos/blob/b31a14543a61517ba0675a6326d231e0ab09f184/tb3_worlds/launch/turtlebot_spawner.launch.py#L57-L60
Tested both models a few time and we're good to go but I didn't handle other values than  (`3` or `4`)

2024-12-13 22:11 UTC, sea-bass commented
Oh, I was basing my branch on yours. I think you should merge this to `main` first and then I will clean up for jazzy

2024-12-13 22:12 UTC, sea-bass commented on tb3_worlds/configs/turtlebot3_bridge.yaml
> +  gz_topic_name: "/world/default/model/turtlebot/link/camera_link/sensor/intel_realsense_r200_depth/image"
I had to make this `turtlebot3`, not `turtlebot`. Did you change anything, or is this a typo?

Anyways I will test again when I get a chance

2024-12-13 22:48 UTC, elsayedelsheikh commented on tb3_worlds/configs/turtlebot3_bridge.yaml
> +  gz_topic_name: "/world/default/model/turtlebot/link/camera_link/sensor/intel_realsense_r200_depth/image"
Yes, I've updated this to use `turtlebot` for both models, so it works now:
https://github.com/sea-bass/turtlebot3_behavior_demos/blob/b31a14543a61517ba0675a6326d231e0ab09f184/tb3_worlds/launch/tb3_world.launch.py#L62-L64

It's fine to change the robot name for TurtleBot4, but not for the TurtleBot3 model. I think we shouldn't allow this as an option in the launch file because changing it would interfere with the image bridge.

2024-12-13 23:39 UTC, elsayedelsheikh commented on tb3_worlds/configs/nav2_params.yaml
> +/**:
TwistStamped messages were disabled by default for jazzy
- https://discourse.ros.org/t/notice-nav2-migrated-to-twiststamped-to-replace-twist-for-cmd-vel-topics/40944
- https://discourse.ros.org/t/nav2-support-for-twiststamped-available-rolling-jazzy/35995

2024-12-13 23:42 UTC, elsayedelsheikh commented on tb3_worlds/configs/nav2_params.yaml
> +    enable_stamped_cmd_vel: true
TwistStamped messages were disabled by default for jazzy
- https://discourse.ros.org/t/notice-nav2-migrated-to-twiststamped-to-replace-twist-for-cmd-vel-topics/40944
- https://discourse.ros.org/t/nav2-support-for-twiststamped-available-rolling-jazzy/35995

2024-12-14 01:11 UTC, sea-bass reviewed
OK -- tested again and now both the TurtleBot 3 and 4 models move! yay.

I still found inconsistencies between the block spawn and navigation poses.

Seems like now the Gazebo world and `map` frames are off by this `0.6, 0.6` offset, so the block spawning needs to be handled differently. See my comments.

2024-12-14 16:13 UTC, sea-bass approved these changes
OK -- this is all working now.

Thanks for all your work @elsayedelsheikh!

2024-12-14 16:13 UTC, merged

2024-12-14 17:01 UTC, elsayedelsheikh commented
It was a pleasure working on this project. 
Feel free to reach out if there are any additional tasks or future projects :)